name: Build-Docker-Image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Sprawdzenie repozytorium
      - name: Checkout code
        uses: actions/checkout@v3

      # Logowanie do Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Budowanie i wysyłanie obrazu Docker za pomocą docker-compose
      - name: Build and push Docker image
        run: |
          docker-compose build
          docker-compose push
