#name: Build-Docker-Image
#
#on:
#  pull_request:
#    branches:
#      - main
#  push:
#    branches:
#      - main
#  workflow_dispatch:
#
#jobs:
#  build-and-push:
#    runs-on: ubuntu-latest
#
#    steps:
#      # Sprawdzenie repozytorium
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#
#        # Budowanie aplikacji backend
#      - name: Set execute permissions for Maven Wrapper
#        run: chmod +x backend/bank-application-backend/mvnw
#
#      - name: Build the backend application
#        run: |
#          cd backend/bank-application-backend
#          ./mvnw clean package -DskipTests
#
#      # Instalacja Docker Compose
#      - name: Install Docker Compose
#        run: |
#          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#          docker-compose --version
#
#      # Logowanie do Docker Hub
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      # Budowanie obrazów backendu i frontendu oraz wysyłanie ich do Docker Hub
#      - name: Build and push Docker images
#        run: |
#          docker-compose build
#          docker-compose push
name: Docker Images

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Sprawdzenie repozytorium
      - name: Checkout code
        uses: actions/checkout@v3

      # Konfiguracja JDK 21 (dla backendu)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Uruchomienie bazy danych PostgreSQL
      - name: Start PostgreSQL container
        run: |
          docker run -d --name postgres \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_DB=bank_db \
            -p 5432:5432 postgres:16
          docker ps

      # Budowanie backendu
      - name: Build the backend application
        run: |
          chmod +x backend/bank-application-backend/mvnw
          cd backend/bank-application-backend
          ./mvnw clean package -DskipTests

      # Instalacja Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Logowanie do Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Budowanie i wypychanie obrazu backendu
      - name: Build and push backend image
        run: |
          docker build -t kamildoniek/bank-backend:latest ./backend/bank-application-backend
          docker push kamildoniek/bank-backend:latest

      # Budowanie i wypychanie obrazu frontend-u
      - name: Build and push frontend image
        run: |
          docker build -t kamildoniek/bank-frontend:latest ./frontend
          docker push kamildoniek/bank-frontend:latest