name: Security Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - security-check-test
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency Check
        uses: jeremylong/gh-action-dependency-check@v4
        with:
          project: bank-application
          scanpath: ./backend/bank-application-backend
          format: ALL
