name: Trivy Security Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - security-check-test
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Docker version
        run: docker --version || echo "Docker not installed"

      - name: Fix conflicting Docker packages
        run: |
          sudo apt-get remove -y containerd containerd.io || echo "No conflicting packages"
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Run Trivy Dependency Scan
        run: |
          docker run --rm \
            -v $(pwd):/src \
            aquasec/trivy:latest filesystem \
            --scanners vuln,secret,license \
            --exit-code 1 \
            --no-progress \
            --severity HIGH,CRITICAL \
            ./backend/bank-application-backend
